# -*- coding: utf-8 -*-
"""Log/Linear/Split ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4tp23RP2v5Ra1QVvC4Ff-AkR6uW4Gjv
"""

import pandas as pd
from sklearn.model_selection import train_test_split

# Load dataset
df = pd.read_csv("ai_resume_screening (1).csv")

# Remove skills_match_score column
df = df.drop(columns=["skills_match_score"])

# Split features and target
X = df.drop(columns=["shortlisted"])
y = df["shortlisted"]

# 80-20 split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Combine X and y back for export
train_data = pd.concat([X_train, y_train], axis=1)
test_data = pd.concat([X_test, y_test], axis=1)

# Export CSV files
train_data.to_csv("train_data.csv", index=False)
test_data.to_csv("test_data.csv", index=False)

print("Train and test CSV files created successfully.")

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error, classification_report

# 1. Load the datasets
train_df = pd.read_csv('train_data.csv')
test_df = pd.read_csv('test_data.csv')

# Convert target 'shortlisted' to numerical (1 for Yes, 0 for No)
train_df['shortlisted'] = train_df['shortlisted'].map({'Yes': 1, 'No': 0})
test_df['shortlisted'] = test_df['shortlisted'].map({'Yes': 1, 'No': 0})


train_df = pd.get_dummies(train_df, columns=['education_level'], drop_first=True)
test_df = pd.get_dummies(test_df, columns=['education_level'], drop_first=True)

for col in set(train_df.columns) - set(test_df.columns):
    test_df[col] = 0
test_df = test_df[train_df.columns]

X_train = train_df.drop('shortlisted', axis=1)
y_train = train_df['shortlisted']
X_test = test_df.drop('shortlisted', axis=1)
y_test = test_df['shortlisted']

lr = LinearRegression()
lr.fit(X_train, y_train)


y_pred_continuous = lr.predict(X_test)

# 6. Convert continuous predictions to binary (0 or 1) by rounding at threshold 0.5
y_pred_binary = np.where(y_pred_continuous >= 0.5, 1, 0)

# 7. Evaluate Performance
accuracy = accuracy_score(y_test, y_pred_binary)
mse = mean_squared_error(y_test, y_pred_continuous)

print(f"Linear Regression Accuracy (after rounding): {accuracy:.4f}")
print(f"Mean Squared Error: {mse:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_binary))

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

train_df = pd.read_csv('train_data.csv')
test_df = pd.read_csv('test_data.csv')

train_df['shortlisted'] = train_df['shortlisted'].map({'Yes': 1, 'No': 0})
test_df['shortlisted'] = test_df['shortlisted'].map({'Yes': 1, 'No': 0})

train_df = pd.get_dummies(train_df, columns=['education_level'], drop_first=True)
test_df = pd.get_dummies(test_df, columns=['education_level'], drop_first=True)

for col in set(train_df.columns) - set(test_df.columns):
    test_df[col] = 0
test_df = test_df[train_df.columns]

X_train = train_df.drop('shortlisted', axis=1)
y_train = train_df['shortlisted']
X_test = test_df.drop('shortlisted', axis=1)
y_test = test_df['shortlisted']


log_reg = LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train, y_train)


y_pred = log_reg.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Logistic Regression Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# @title
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

# 1. Load and Train the Model (Same as before)
train_df = pd.read_csv('train_data.csv')
train_df['shortlisted'] = train_df['shortlisted'].map({'Yes': 1, 'No': 0})

# We save the original column structure for later use
train_processed = pd.get_dummies(train_df, columns=['education_level'], drop_first=True)
X_train = train_processed.drop('shortlisted', axis=1)
y_train = train_processed['shortlisted']

# List of columns to ensure user input matches training data
feature_cols = list(X_train.columns)

model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# 2. Prediction Function
def predict_candidate():
    print("\n--- Candidate Shortlisting Prediction ---")
    try:
        # Taking inputs
        years_exp = float(input("Enter Years of Experience: "))
        projects = int(input("Enter Project Count: "))
        resume_len = int(input("Enter Resume Length (words): "))
        github_act = int(input("Enter GitHub Activity (contributions): "))

        print("\nEducation Levels: Bachelors, Masters, PhD, High School")
        edu = input("Enter Education Level: ").strip()

        # Create a dictionary for the input data
        # Initialize all features to 0
        input_data = {col: 0 for col in feature_cols}

        # Fill in numerical features
        input_data['years_experience'] = years_exp
        input_data['project_count'] = projects
        input_data['resume_length'] = resume_len
        input_data['github_activity'] = github_act

        # Handle One-Hot Encoding for Education Level
        # Note: 'Bachelors' is the 'dropped' column, so if edu is 'Bachelors',
        # all 'education_level_...' columns remain 0.
        edu_col = f"education_level_{edu}"
        if edu_col in input_data:
            input_data[edu_col] = 1

        # Convert to DataFrame to match model input format
        input_df = pd.DataFrame([input_data])

        # Predict
        prediction = model.predict(input_df)[0]
        probability = model.predict_proba(input_df)[0][1]

        # Result
        print("\n" + "="*30)
        if prediction == 1:
            print(f"RESULT: Shortlisted (Yes)")
        else:
            print(f"RESULT: Not Shortlisted (No)")
        print(f"Confidence: {probability:.2%}")
        print("="*30)

    except ValueError:
        print("Invalid input! Please enter numbers for experience, counts, and length.")

# 3. Run the interactive part
if __name__ == "__main__":
    while True:
        predict_candidate()
        again = input("\nPredict for another candidate? (yes/no): ").lower()
        if again != 'yes':
            break